
REWARD_UNIT = 1 / 10000  # CHANGE TO 0 FOR TESTING SHAPES

LOSE_REWARD = - 1000.0 * REWARD_UNIT
WIN_REWARD = 1000.0 * REWARD_UNIT
LVL_UP_REWARD = 300.0 * REWARD_UNIT  # 40 * REWARD_UNIT
MOB_KILL_REWARD = 80.0 * REWARD_UNIT  # 10 * REWARD_UNIT
DMG_DEAL_TO_PLAYER_REWARD_PER_DAMAGE = 6.0 * REWARD_UNIT  # 1.2 * REWARD_UNIT
DMG_DEAL_TO_MOB_REWARD_PER_DAMAGE = 4.0 * REWARD_UNIT  # 0.8 * REWARD_UNIT
DMG_TAKE_REWARD_PER_DAMAGE = - 3.0 * REWARD_UNIT  # - 1.0 * REWARD_UNIT
HEAL_REWARD_PER_HEAL = 6.0 * REWARD_UNIT
MOVE_REWARD = 0.0 * REWARD_UNIT
DO_NOTHING_REWARD = - 0.1 * REWARD_UNIT


TEST_REWARD = 1.0 * REWARD_UNIT
