
REWARD_UNIT = 1 / 10000 * 0 # UNDER TESTING

LOSE_REWARD = - 1000 * REWARD_UNIT
WIN_REWARD = 1000 * REWARD_UNIT
LVL_UP_REWARD = 40 * REWARD_UNIT
MOB_KILL_REWARD = 10 * REWARD_UNIT
DMG_DEAL_TO_PLAYER_REWARD_PER_DAMAGE = 1.2 * REWARD_UNIT
DMG_DEAL_TO_MOB_REWARD_PER_DAMAGE = 0.8 * REWARD_UNIT
DMG_TAKE_REWARD_PER_DAMAGE = - REWARD_UNIT
HEAL_REWARD_PER_HEAL = REWARD_UNIT


TEST_REWARD = 0.01
